version: "2"

services:
  mc:
    image: itzg/minecraft-server:multiarch
    networks:
      - proxy  
    ports:
      - 25565
    tty: true
    stdin_open: true
    restart: always
    environment:
      EULA: "TRUE"
      TYPE: "FTBA"
      FTB_MODPACK_ID: "${MOD_ID}"
    labels:
      - "traefik.enable=false"