version: "2"

services:
  mc:
    image: itzg/minecraft-server:multiarch
    networks:
      - proxy  
    ports:
      - "80:25565"
      - "443:25565"
    tty: true
    stdin_open: true
    restart: always
    environment:
      EULA: "TRUE"
      TYPE: "FTBA"
      FTB_MODPACK_ID: "${MOD_ID}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wp-${TRAEFIK_NAME}.entrypoints=http"
      - "traefik.http.routers.wp-${TRAEFIK_NAME}.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.middlewares.wp-${TRAEFIK_NAME}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.wp-${TRAEFIK_NAME}.middlewares=wp-${TRAEFIK_NAME}-https-redirect"
      - "traefik.http.routers.wp-${TRAEFIK_NAME}-secure.entrypoints=https"
      - "traefik.http.routers.wp-${TRAEFIK_NAME}-secure.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.wp-${TRAEFIK_NAME}-secure.tls=true"
      - "traefik.http.routers.wp-${TRAEFIK_NAME}-secure.tls.certresolver=http"
      - "traefik.http.routers.wp-${TRAEFIK_NAME}-secure.service=wp-${TRAEFIK_NAME}"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external:
      name: proxy