version: "2"

services:
  db:
    image: mysql:5.7
    networks:
      - proxy
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    networks:
      - proxy  
    links:
      - db:mysql
    ports:
      - 80
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wp-${TRAEFIK_NAME}.entrypoints=http"
      - "traefik.http.routers.wp-${TRAEFIK_NAME}.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.middlewares.wp-${TRAEFIK_NAME}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.wp-${TRAEFIK_NAME}.middlewares=wp-${TRAEFIK_NAME}-https-redirect"
      - "traefik.http.routers.wp-${TRAEFIK_NAME}-secure.entrypoints=https"
      - "traefik.http.routers.wp-${TRAEFIK_NAME}-secure.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.wp-${TRAEFIK_NAME}-secure.tls=true"
      - "traefik.http.routers.wp-${TRAEFIK_NAME}-secure.tls.certresolver=http"
      - "traefik.http.routers.wp-${TRAEFIK_NAME}-secure.service=wp-${TRAEFIK_NAME}"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external:
      name: proxy