version: "2"

services:
  gitea:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - ROOT_URL=http://${TRAEFIK_DOMAIN}:80
      - SSH_DOMAIN=${TRAEFIK_DOMAIN}:22
    restart: always
    ports:
      - 3000
      - 22 # maybe we need an entrypoint for this
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea-${TRAEFIK_NAME}.entrypoints=http"
      - "traefik.http.routers.gitea-${TRAEFIK_NAME}.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.middlewares.gitea-${TRAEFIK_NAME}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.gitea-${TRAEFIK_NAME}.middlewares=gitea-${TRAEFIK_NAME}-https-redirect"
      - "traefik.http.routers.gitea-${TRAEFIK_NAME}-secure.entrypoints=https"
      - "traefik.http.routers.gitea-${TRAEFIK_NAME}-secure.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.gitea-${TRAEFIK_NAME}-secure.tls=true"
      - "traefik.http.routers.gitea-${TRAEFIK_NAME}-secure.tls.certresolver=http"
      - "traefik.http.routers.gitea-${TRAEFIK_NAME}-secure.service=gitea-${TRAEFIK_NAME}"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.gitea-${TRAEFIK_NAME}.loadbalancer.server.port=3000"

  gitea-db:
    image: postgres:alpine
    ports:
      - 5432
    restart: always
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PW}
      - POSTGRES_DB=gitea
    networks:
      - proxy

networks:
  proxy:
    external:
      name: proxy